/**
 * Team Spawning Skill
 * Dynamically creates and manages agent teams with resource tracking.
 *
 * @module skills/team_spawning
 */

import Joi from "joi";
import { v4 as uuidv4 } from "uuid";
import type { AgentConfig } from "../src/types/index.js";
import { createLogger } from "../src/utils/logger.js";

const logger = createLogger("TeamSpawningSkill");

// ---------------------------------------------------------------------------
// Types & Interfaces
// ---------------------------------------------------------------------------

/** Lifecycle state of a spawned agent */
export type AgentStatus = "initialising" | "idle" | "busy" | "draining" | "stopped" | "error";

/** Lifecycle state of a team */
export type TeamStatus = "active" | "scaling" | "draining" | "dissolved";

/** Resource usage snapshot for a single agent */
export interface AgentResourceUsage {
  tokensUsed: number;
  estimatedCostUsd: number;
  memoryMb: number;
  tasksCompleted: number;
  tasksInProgress: number;
  lastActivityAt: string | null;
}

/** A live agent instance */
export interface AgentInstance {
  agentId: string;
  teamId: string;
  config: AgentConfig;
  status: AgentStatus;
  spawnedAt: string;
  updatedAt: string;
  resources: AgentResourceUsage;
}

/** Health snapshot for a team */
export interface TeamHealth {
  teamId: string;
  name: string;
  status: TeamStatus;
  agents: AgentInstance[];
  totalTokensUsed: number;
  totalEstimatedCostUsd: number;
  activeTaskCount: number;
  createdAt: string;
  updatedAt: string;
}

/** Configuration supplied when spawning a full team */
export interface SpawnTeamConfig {
  name: string;
  role: string;
  agents: AgentConfig[];
  maxConcurrency?: number;
  timeoutMs?: number;
  metadata?: Record<string, unknown>;
}

/** Minimal configuration for spawning a single agent */
export interface SpawnAgentConfig {
  name: string;
  model: string;
  systemPrompt: string;
  maxTokens?: number;
  temperature?: number;
  tools?: string[];
  metadata?: Record<string, unknown>;
}

/** A task routed to a team */
export interface TeamTask {
  taskId: string;
  teamId: string;
  payload: unknown;
  assignedAgentId: string | null;
  status: "queued" | "running" | "completed" | "failed";
  createdAt: string;
  startedAt: string | null;
  completedAt: string | null;
  result: unknown;
  error: string | null;
}

// ---------------------------------------------------------------------------
// Validation schemas
// ---------------------------------------------------------------------------

const agentConfigSchema = Joi.object({
  id: Joi.string().optional(), // generated if absent
  name: Joi.string().min(1).max(128).required(),
  model: Joi.string().min(1).required(),
  systemPrompt: Joi.string().min(1).required(),
  maxTokens: Joi.number().integer().min(1).default(4096),
  temperature: Joi.number().min(0).max(1).default(0.7),
  tools: Joi.array().items(Joi.string()).default([]),
  metadata: Joi.object().unknown(true).default({}),
});

const spawnTeamSchema = Joi.object({
  name: Joi.string().min(1).max(256).required(),
  role: Joi.string().min(1).max(512).required(),
  agents: Joi.array().items(agentConfigSchema).min(1).required(),
  maxConcurrency: Joi.number().integer().min(1).default(5),
  timeoutMs: Joi.number().integer().min(0).default(300_000),
  metadata: Joi.object().unknown(true).default({}),
});

const spawnAgentSchema = Joi.object({
  id: Joi.string().optional(), // generated by the skill if absent
  name: Joi.string().min(1).max(128).required(),
  model: Joi.string().min(1).required(),
  systemPrompt: Joi.string().min(1).required(),
  maxTokens: Joi.number().integer().min(1).default(4096),
  temperature: Joi.number().min(0).max(1).default(0.7),
  tools: Joi.array().items(Joi.string()).default([]),
  metadata: Joi.object().unknown(true).default({}),
});

// ---------------------------------------------------------------------------
// Custom errors
// ---------------------------------------------------------------------------

export class TeamNotFoundError extends Error {
  constructor(teamId: string) {
    super(`Team not found: ${teamId}`);
    this.name = "TeamNotFoundError";
  }
}

export class AgentNotFoundError extends Error {
  constructor(agentId: string) {
    super(`Agent not found: ${agentId}`);
    this.name = "AgentNotFoundError";
  }
}

export class TeamSpawningValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TeamSpawningValidationError";
  }
}

export class TeamScalingError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TeamScalingError";
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Cost per token (approximate, claude-sonnet tier) in USD */
const COST_PER_TOKEN_USD = 0.000_003;

/** Baseline memory footprint per agent in MB */
const BASE_MEMORY_MB = 64;

function newResourceUsage(): AgentResourceUsage {
  return {
    tokensUsed: 0,
    estimatedCostUsd: 0,
    memoryMb: BASE_MEMORY_MB,
    tasksCompleted: 0,
    tasksInProgress: 0,
    lastActivityAt: null,
  };
}

function buildAgentInstance(config: AgentConfig, teamId: string): AgentInstance {
  return {
    agentId: config.id ?? `agent-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    teamId,
    config,
    status: "idle",
    spawnedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    resources: newResourceUsage(),
  };
}

// ---------------------------------------------------------------------------
// TeamSpawningSkill
// ---------------------------------------------------------------------------

/**
 * TeamSpawningSkill
 *
 * Manages the full lifecycle of agent teams: spawning, scaling, task
 * assignment, resource tracking, and graceful teardown.
 *
 * @example
 * ```ts
 * const skill = new TeamSpawningSkill();
 * const team = skill.spawnTeam({ name: 'ReviewTeam', role: 'code-review', agents: [...] });
 * await skill.assignTaskToTeam(team.teamId, { pr: 42 });
 * skill.scaleTeam(team.teamId, 5);
 * ```
 */
export class TeamSpawningSkill {
  /** Live teams keyed by teamId */
  private readonly teams = new Map<string, TeamHealth>();

  /** All agent instances keyed by agentId */
  private readonly agents = new Map<string, AgentInstance>();

  /** Task queue keyed by taskId */
  private readonly tasks = new Map<string, TeamTask>();

  // -------------------------------------------------------------------------
  // Public API
  // -------------------------------------------------------------------------

  /**
   * Creates a fully-configured team of agents.
   *
   * @param teamConfig - Team configuration including agents array
   * @returns The newly created TeamHealth snapshot
   * @throws {TeamSpawningValidationError} on invalid input
   */
  spawnTeam(teamConfig: SpawnTeamConfig): TeamHealth {
    const { error, value } = spawnTeamSchema.validate(teamConfig, { abortEarly: false });
    if (error) {
      throw new TeamSpawningValidationError(error.message);
    }

    const validated = value as Required<SpawnTeamConfig>;
    const teamId = uuidv4();
    const now = new Date().toISOString();

    const agentInstances: AgentInstance[] = validated.agents.map((raw) => {
      const agentConfig: AgentConfig = {
        ...raw,
        id: raw.id ?? uuidv4(),
      };
      const instance = buildAgentInstance(agentConfig, teamId);
      this.agents.set(instance.agentId, instance);
      logger.debug("Agent spawned", {
        agentId: instance.agentId,
        teamId,
        model: agentConfig.model,
      });
      return instance;
    });

    const team: TeamHealth = {
      teamId,
      name: validated.name,
      status: "active",
      agents: agentInstances,
      totalTokensUsed: 0,
      totalEstimatedCostUsd: 0,
      activeTaskCount: 0,
      createdAt: now,
      updatedAt: now,
    };

    this.teams.set(teamId, team);
    logger.info("Team spawned", {
      teamId,
      name: validated.name,
      agentCount: agentInstances.length,
    });

    return team;
  }

  /**
   * Spawns a standalone agent not bound to any team.
   *
   * @param agentConfig - Agent configuration
   * @returns The new AgentInstance
   * @throws {TeamSpawningValidationError} on invalid input
   */
  spawnAgent(agentConfig: SpawnAgentConfig): AgentInstance {
    const { error, value } = spawnAgentSchema.validate(agentConfig, { abortEarly: false });
    if (error) {
      throw new TeamSpawningValidationError(error.message);
    }

    const validated = value as Required<SpawnAgentConfig>;
    const config: AgentConfig = {
      id: uuidv4(),
      name: validated.name,
      model: validated.model,
      systemPrompt: validated.systemPrompt,
      maxTokens: validated.maxTokens,
      temperature: validated.temperature,
      tools: validated.tools,
      metadata: validated.metadata,
    };

    const instance = buildAgentInstance(config, "standalone");
    this.agents.set(instance.agentId, instance);
    logger.info("Standalone agent spawned", { agentId: instance.agentId, model: config.model });
    return instance;
  }

  /**
   * Gracefully shuts down an agent and removes it from its team (if any).
   *
   * @param agentId - ID of the agent to despawn
   * @throws {AgentNotFoundError} if the agent does not exist
   */
  despawnAgent(agentId: string): void {
    const agent = this.agents.get(agentId);
    if (!agent) {
      throw new AgentNotFoundError(agentId);
    }

    // Drain in-progress tasks
    agent.status = "draining";
    agent.updatedAt = new Date().toISOString();
    logger.debug("Agent draining", { agentId });

    // Remove from team
    const team = this.teams.get(agent.teamId);
    if (team) {
      team.agents = team.agents.filter((a) => a.agentId !== agentId);
      team.updatedAt = new Date().toISOString();
    }

    agent.status = "stopped";
    this.agents.delete(agentId);
    logger.info("Agent despawned", { agentId, teamId: agent.teamId });
  }

  /**
   * Scales a team's agent pool up or down to the target count.
   * Scale-up uses the configuration of the first existing agent as a template.
   * Scale-down despawns the most recently added idle agents first.
   *
   * @param teamId - ID of the team to scale
   * @param targetCount - Desired number of agents in the team
   * @throws {TeamNotFoundError} if the team does not exist
   * @throws {TeamScalingError} if scaling is not possible
   */
  scaleTeam(teamId: string, targetCount: number): TeamHealth {
    if (!Number.isInteger(targetCount) || targetCount < 0) {
      throw new TeamScalingError(`targetCount must be a non-negative integer, got: ${targetCount}`);
    }

    const team = this._getTeam(teamId);
    const currentCount = team.agents.length;

    if (targetCount === currentCount) {
      logger.debug("Scale no-op: team already at target count", { teamId, targetCount });
      return team;
    }

    team.status = "scaling";
    team.updatedAt = new Date().toISOString();

    if (targetCount > currentCount) {
      // Scale up: clone first agent's config as template
      const template = team.agents[0];
      if (!template) {
        throw new TeamScalingError(
          `Cannot scale up team "${teamId}" — no existing agent to use as template`,
        );
      }
      const toAdd = targetCount - currentCount;
      for (let i = 0; i < toAdd; i++) {
        const newConfig: AgentConfig = {
          ...template.config,
          id: uuidv4(),
          name: `${template.config.name}-${i + currentCount + 1}`,
        };
        const newAgent = buildAgentInstance(newConfig, teamId);
        this.agents.set(newAgent.agentId, newAgent);
        team.agents.push(newAgent);
        logger.debug("Scale-up: agent added", { agentId: newAgent.agentId, teamId });
      }
    } else {
      // Scale down: remove idle agents from the tail first
      const toRemove = currentCount - targetCount;
      const sortedByIdleness = [...team.agents]
        .reverse()
        .filter((a) => a.status === "idle")
        .slice(0, toRemove);

      if (sortedByIdleness.length < toRemove) {
        logger.warn("Scale-down: some busy agents cannot be removed immediately", {
          teamId,
          requested: toRemove,
          removable: sortedByIdleness.length,
        });
      }

      for (const agent of sortedByIdleness) {
        this.despawnAgent(agent.agentId);
      }
    }

    team.status = "active";
    team.updatedAt = new Date().toISOString();
    logger.info("Team scaled", { teamId, from: currentCount, to: team.agents.length });
    return team;
  }

  /**
   * Returns the current health snapshot for a team.
   *
   * @param teamId - Team identifier
   * @returns Readonly TeamHealth snapshot
   * @throws {TeamNotFoundError}
   */
  getTeamStatus(teamId: string): Readonly<TeamHealth> {
    const team = this._getTeam(teamId);
    // Recompute aggregated resource totals
    team.totalTokensUsed = team.agents.reduce((s, a) => s + a.resources.tokensUsed, 0);
    team.totalEstimatedCostUsd = team.agents.reduce((s, a) => s + a.resources.estimatedCostUsd, 0);
    team.activeTaskCount = team.agents.reduce((s, a) => s + a.resources.tasksInProgress, 0);
    return team;
  }

  /**
   * Returns all currently active teams.
   */
  listTeams(): TeamHealth[] {
    return Array.from(this.teams.values()).filter((t) => t.status !== "dissolved");
  }

  /**
   * Assigns a task to the least-busy agent in a team.
   *
   * @param teamId - Target team ID
   * @param task - Arbitrary task payload
   * @returns The created TeamTask
   * @throws {TeamNotFoundError} if the team is unknown
   * @throws {TeamScalingError} if no agents are available
   */
  assignTaskToTeam(teamId: string, task: unknown): TeamTask {
    const team = this._getTeam(teamId);

    // Select the idle agent with the fewest completed tasks (least worn)
    const idleAgents = team.agents
      .filter((a) => a.status === "idle")
      .sort((a, b) => a.resources.tasksCompleted - b.resources.tasksCompleted);

    if (idleAgents.length === 0) {
      throw new TeamScalingError(
        `No idle agents available in team "${teamId}". Consider scaling up.`,
      );
    }

    // idleAgents.length === 0 already checked above — safe to assert non-null
    const selectedAgent = idleAgents[0]!;
    selectedAgent.status = "busy";
    selectedAgent.resources.tasksInProgress += 1;
    selectedAgent.resources.lastActivityAt = new Date().toISOString();
    selectedAgent.updatedAt = new Date().toISOString();

    const teamTask: TeamTask = {
      taskId: uuidv4(),
      teamId,
      payload: task,
      assignedAgentId: selectedAgent.agentId,
      status: "running",
      createdAt: new Date().toISOString(),
      startedAt: new Date().toISOString(),
      completedAt: null,
      result: null,
      error: null,
    };

    this.tasks.set(teamTask.taskId, teamTask);
    team.activeTaskCount += 1;
    team.updatedAt = new Date().toISOString();

    logger.info("Task assigned to agent", {
      taskId: teamTask.taskId,
      teamId,
      agentId: selectedAgent.agentId,
    });

    return teamTask;
  }

  /**
   * Records token usage for an agent and updates cost estimates.
   *
   * @param agentId - Agent that consumed tokens
   * @param tokens - Number of tokens used
   */
  recordTokenUsage(agentId: string, tokens: number): void {
    const agent = this.agents.get(agentId);
    if (!agent) {
      return;
    }
    agent.resources.tokensUsed += tokens;
    agent.resources.estimatedCostUsd += tokens * COST_PER_TOKEN_USD;
    agent.updatedAt = new Date().toISOString();
  }

  /**
   * Marks a task as completed and updates agent resource counters.
   *
   * @param taskId - Task to complete
   * @param result - Task output
   */
  completeTask(taskId: string, result: unknown): TeamTask {
    const task = this.tasks.get(taskId);
    if (!task) {
      throw new Error(`Task not found: ${taskId}`);
    }

    task.status = "completed";
    task.result = result;
    task.completedAt = new Date().toISOString();

    const agent = this.agents.get(task.assignedAgentId ?? "");
    if (agent) {
      agent.resources.tasksInProgress = Math.max(0, agent.resources.tasksInProgress - 1);
      agent.resources.tasksCompleted += 1;
      agent.status = agent.resources.tasksInProgress === 0 ? "idle" : "busy";
      agent.updatedAt = new Date().toISOString();
    }

    const team = this.teams.get(task.teamId);
    if (team) {
      team.activeTaskCount = Math.max(0, team.activeTaskCount - 1);
      team.updatedAt = new Date().toISOString();
    }

    logger.debug("Task completed", { taskId, teamId: task.teamId });
    return task;
  }

  // -------------------------------------------------------------------------
  // Private helpers
  // -------------------------------------------------------------------------

  private _getTeam(teamId: string): TeamHealth {
    const team = this.teams.get(teamId);
    if (!team) {
      throw new TeamNotFoundError(teamId);
    }
    return team;
  }
}
