/**
 * OpenClaw Teams — Core TypeScript Interfaces & Types
 * All shared domain types for the multi-agent LangGraph system.
 */

// ---------------------------------------------------------------------------
// Graph / Workflow State
// ---------------------------------------------------------------------------

export interface GraphState {
  /** Raw input provided by the user to kick off the workflow */
  userInput: string;

  /** Parsed and structured requirements extracted from userInput */
  requirements: Record<string, unknown>;

  /** Name of the node currently executing */
  currentStep: string;

  /** Ordered list of nodes that have already completed */
  stepHistory: string[];

  /** Key decisions made by the orchestrator throughout the run */
  decisions: Decision[];

  /** Teams that have been spawned during this workflow execution */
  teamsSpawned: TeamConfig[];

  /** Collected results keyed by team identifier */
  teamResults: Record<string, TeamResult>;

  /** High-level deployment / architecture plan produced after planning phase */
  finalPlan: FinalPlan | null;

  /** Whether the system is ready for deployment after validation */
  deploymentReady: boolean;

  /** ISO-8601 timestamp when the workflow started */
  startTime: string;

  /** ISO-8601 timestamp when the workflow ended (null while in progress) */
  endTime: string | null;

  /** Accumulated errors across all steps */
  errors: WorkflowError[];
}

export interface Decision {
  step: string;
  timestamp: string;
  description: string;
  rationale: string;
  outcome: string;
}

export interface FinalPlan {
  architecture: string;
  agents: AgentConfig[];
  workflows: WorkflowDefinition[];
  deploymentConfig: DeploymentConfig;
  estimatedComplexity: "low" | "medium" | "high";
  generatedAt: string;
}

export interface WorkflowError {
  step: string;
  timestamp: string;
  message: string;
  retryable: boolean;
  stack?: string;
}

// ---------------------------------------------------------------------------
// Agent
// ---------------------------------------------------------------------------

export interface AgentConfig {
  /** Unique identifier for this agent — generated by spawnAgent if not supplied */
  id?: string;

  /** Human-readable display name */
  name: string;

  /** Anthropic model ID to use (e.g. "claude-opus-4-6", "claude-sonnet-4-6") */
  model: string;

  /** System-level instructions for the agent */
  systemPrompt: string;

  /** Maximum number of tokens to generate in a single response */
  maxTokens: number;

  /** Sampling temperature (0.0 – 1.0) */
  temperature: number;

  /** Tool / function names this agent is allowed to call */
  tools: string[];

  /** Arbitrary metadata attached to this agent configuration */
  metadata: Record<string, unknown>;
}

export interface AgentMessage {
  /** Message sender identifier */
  from: string;

  /** Message recipient identifier */
  to: string;

  /** ISO-8601 timestamp */
  timestamp: string;

  /** Message type discriminator */
  type: "request" | "response" | "broadcast" | "error";

  /** Message body */
  content: string;

  /** Optional structured payload */
  payload?: Record<string, unknown>;

  /** Correlation ID for request/response pairing */
  correlationId?: string;
}

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export interface TeamConfig {
  /** Unique team identifier */
  teamId: string;

  /** Human-readable team name */
  name: string;

  /** Purpose / responsibility of this team */
  role: string;

  /** Agents that belong to this team */
  agents: AgentConfig[];

  /** Maximum concurrent tasks this team may run */
  maxConcurrency: number;

  /** Timeout in milliseconds for a full team task */
  timeoutMs: number;
}

export interface TeamResult {
  teamId: string;
  success: boolean;
  output: unknown;
  artifacts: Artifact[];
  duration: number;
  errors: WorkflowError[];
  completedAt: string;
}

export interface Artifact {
  /** Artifact type discriminator */
  type: "code" | "config" | "documentation" | "test" | "schema" | "other";

  /** File path or identifier */
  path: string;

  /** Text content of the artifact */
  content: string;

  /** Programming language or format (e.g. "typescript", "yaml") */
  language?: string;
}

// ---------------------------------------------------------------------------
// Workflow Definition
// ---------------------------------------------------------------------------

export interface WorkflowDefinition {
  /** Unique identifier */
  id: string;

  /** Human-readable name */
  name: string;

  /** Short description */
  description: string;

  /** Ordered list of step names */
  steps: WorkflowStep[];

  /** Entry point step name */
  entryPoint: string;

  /** Step name(s) that complete the workflow */
  exitPoints: string[];

  /** Maximum total runtime in milliseconds */
  timeoutMs: number;

  /** Workflow-level metadata */
  metadata: Record<string, unknown>;
}

export interface WorkflowStep {
  /** Step identifier (must be unique within the workflow) */
  id: string;

  /** Human-readable label */
  label: string;

  /** Agent responsible for this step */
  agentId: string;

  /** Input schema definition (JSON Schema object) */
  inputSchema: Record<string, unknown>;

  /** Output schema definition (JSON Schema object) */
  outputSchema: Record<string, unknown>;

  /** Step IDs that this step transitions to on success */
  onSuccess: string[];

  /** Step IDs that this step transitions to on failure */
  onFailure: string[];

  /** Whether this step can be retried on transient failure */
  retryable: boolean;

  /** Maximum retry attempts */
  maxRetries: number;
}

// ---------------------------------------------------------------------------
// Skills / Tools
// ---------------------------------------------------------------------------

export interface SkillDefinition {
  /** Unique slug (snake_case) */
  name: string;

  /** Short description shown to the LLM */
  description: string;

  /** JSON Schema describing the input parameters */
  parameters: Record<string, unknown>;

  /** Expected return type description */
  returnType: string;

  /** Whether this skill requires network access */
  requiresNetwork: boolean;

  /** Tags for discoverability */
  tags: string[];
}

export interface ToolResult {
  /** Tool name that was invoked */
  toolName: string;

  /** Whether the invocation succeeded */
  success: boolean;

  /** Structured output from the tool */
  output: unknown;

  /** Error message if success is false */
  error?: string;

  /** Execution time in milliseconds */
  durationMs: number;

  /** ISO-8601 timestamp of invocation */
  invokedAt: string;
}

// ---------------------------------------------------------------------------
// Deployment
// ---------------------------------------------------------------------------

export interface DeploymentConfig {
  /** Target deployment environment */
  environment: "development" | "staging" | "production";

  /** Container / image registry URL */
  registry?: string;

  /** Image tag to deploy */
  imageTag?: string;

  /** Kubernetes namespace or equivalent */
  namespace?: string;

  /** Number of replicas for the primary service */
  replicas: number;

  /** Resource limits */
  resources: ResourceLimits;

  /** Environment variables to inject */
  envVars: Record<string, string>;

  /** Secrets to mount (names only — values are resolved at deploy time) */
  secrets: string[];

  /** Health-check configuration */
  healthCheck: HealthCheckConfig;
}

export interface ResourceLimits {
  cpuRequest: string;
  cpuLimit: string;
  memoryRequest: string;
  memoryLimit: string;
}

export interface HealthCheckConfig {
  /** HTTP path for readiness/liveness probes */
  path: string;

  /** Port for health checks */
  port: number;

  /** Initial delay before first probe in seconds */
  initialDelaySeconds: number;

  /** How often to probe in seconds */
  periodSeconds: number;

  /** Number of consecutive failures before marking unhealthy */
  failureThreshold: number;
}

// ---------------------------------------------------------------------------
// Health / Observability
// ---------------------------------------------------------------------------

export interface HealthStatus {
  /** Overall system health */
  status: "healthy" | "degraded" | "unhealthy";

  /** ISO-8601 timestamp of last check */
  checkedAt: string;

  /** Individual component statuses */
  components: Record<string, ComponentHealth>;

  /** Uptime in seconds */
  uptimeSeconds: number;

  /** Application version string */
  version: string;
}

export interface ComponentHealth {
  status: "healthy" | "degraded" | "unhealthy";
  message?: string;
  latencyMs?: number;
}
